name: BunkerUtils
version: '1.0-SNAPSHOT'
main: moe.kayla.bunkerutils.BunkerUtils
api-version: 1.16
depend: [ CivModCore, Citadel, NameLayer , Multiverse-Core, Bastion, WorldEdit]
authors: [ Kayla ]
description: A plugin that adds-on to the Citadel plugin commonly contained within the CivCraft Suite. These additions are aimed toward improving the ability to create bunker-fights.
commands:
  bctf:
    description: Set your reinforcement mode, (/bctf <REINMODE> <REINTYPE>)
    aliases: [reinmode, buctf]
    permission: bu.ctf
    usage: "Usage: /bctf [UNREINFORCED|REINFORCE|MODIFY]"
  bctworld:
    description: Saves a worlds reinforcements and makes it an arena that can be accessed.
    aliases: [savearena, bctarena]
    permission: bu.ctworld
    usage: "Usage: /bctworld <NAME> <DESCRIPTION>"
  bactive:
    description: Activates a new arena for a bunker fight.
    aliases: [activatearena, entarena]
    permission: bu.active
    usage: "Usage: /bactive <WORLD>"
  bmod:
    description: Modify an arena in a certain way.
    aliases: [arenamodify, modifyarena]
    permission: bu.ctworld
    usage: "Usage: /bmod <WORLD> [Author|Description|Name] <New Value>"
  setctspawn:
    description: Sets a spawn for a certain team in a certain arena.
    aliases: [setarenaspawn, arenaspawn]
    permission: bu.ctworld
    usage: "Usage: /setctspawn [Defenders|Attackers]"
  arena:
    description: Arena command for joining, and leaving arena's.
    aliases: [a]
    usage: "Usage: /arena for help."
  bctar:
    description: Area reinforce using WorldEdit.
    permission: bu.ctools
    aliases: [barearein, areareinforce]
    usage: "Usage: /bctar <group>"